### ISSUE TITLE
Bug in helm v. 3.3.4-3.4.1

### ISSUE THREAD

**Issue by vs422h** [airshipit/charts#1]
Some syntactically and semantically correct charts are failing because of a bug in Helm.
https://github.com/rook/rook/issues/6851
https://github.com/helm/helm/issues/9019
How to reproduce:
Described in https://github.com/rook/rook/issues/6851
Possible fixes: uplift helm version to 3.5.2 (has been tested locally, demonstrates an expected behavior) in playbooks/vars.yaml.

**Comment by mattmceuen** [comment]
Looks like we've updated to helm v3.5.2 since this issue has been put in, so we should be good here.
